Fix the ScriptHandlers for Composer 2.3 (see #3910)
Description
-----------

Composer 2.3 will currently break our ScriptHandlers, because the PHP and `symfony/process` requirement of Composer are finally bumped up (https://github.com/composer/composer/commit/d2ede370be20aedfc74749bc87394a79ed4c1e52). 

```
Fatal error: Uncaught TypeError: Argument 1 passed to Symfony\Component\Process\Process::__construct() must be of the type array, string given, called in vendor\contao\contao\manager-bundle\src\Composer\ScriptHandler.php on line 69
```

This PR backports the changes from Contao 4.10 to 4.9, where the `symfony/process` cross-compatibility was already introduced.

Commits
-------

383159d5 fix ScriptHandler for Composer 2.3
f2ced6f6 update tests