Add a conflict with nikic/php-parser (see #2002)
Description
-----------

As of version 4.7, the PHP parser supports PHP 8 match expressions, which unfortunately [breaks PHPUnit](https://github.com/nikic/PHP-Parser/pull/672#issuecomment-659343331) under PHP 7.4.

```
ERROR: ParseError - vendor/phpunit/phpunit/src/Framework/MockObject/Builder/ParametersMatch.php:15:35 - Syntax error, unexpected T_MATCH on line 15 (see https://psalm.dev/173)
interface ParametersMatch extends Match


ERROR: ParseError - vendor/phpunit/phpunit/src/Framework/MockObject/Builder/ParametersMatch.php:34:40 - Syntax error, unexpected ';', expecting '{' on line 34 (see https://psalm.dev/173)
    public function with(...$arguments);


ERROR: ParseError - vendor/phpunit/phpunit/src/Framework/MockObject/Builder/ParametersMatch.php:47:40 - Syntax error, unexpected ';', expecting '{' on line 47 (see https://psalm.dev/173)
    public function withAnyParameters();
```

The issue has been reported in https://github.com/nikic/PHP-Parser/issues/690, so I hope it will be fixed in version 4.7.1.

Commits
-------

00ed9a0e Add a conflict with nikic/php-parser